/**
 * Public design-guide data mirrored from the native app's canonical constants.
 * Keep this file aligned with constants/theme.ts and the adjacent palette files
 * in lessgo-react-native when the product system changes.
 */

export const brandStops = [
  { name: 'Sky', value: '#67BDF6' },
  { name: 'Indigo', value: '#5E55E8' },
  { name: 'Magenta', value: '#C637DA' },
] as const;

export const brandAccent = '#5596F2';
export const brandGlow = '#965AFF';

export const splashSpectrum = {
  light: [
    '#C71567',
    '#7E2FC7',
    '#3556D8',
    '#007FAE',
    '#008F72',
    '#668F00',
    '#C87500',
    '#D9472A',
  ],
  dark: [
    '#F72585',
    '#B75CFF',
    '#5E7BFF',
    '#27D8FF',
    '#00D6A3',
    '#A5D613',
    '#FFB21C',
    '#FF704D',
  ],
} as const;

export const domainPalettes = [
  {
    name: 'Events',
    key: 'home',
    purpose: 'Plans, invitations and attendance',
    light: {
      bg: '#F6F7EF',
      surface: '#FFFFFF',
      surface2: '#EDF0E1',
      ink: '#1B1E14',
      muted: '#6E7264',
      accent: '#B4E22E',
      accent2: '#6FBF7A',
      onAccent: '#16190F',
      positive: '#2FA35B',
      negative: '#E5533D',
    },
    dark: {
      bg: '#121110',
      surface: '#1E1B18',
      surface2: '#282420',
      ink: '#F5F2EC',
      muted: '#9A938A',
      accent: '#C7F04A',
      accent2: '#86D98F',
      onAccent: '#141210',
      positive: '#C7F04A',
      negative: '#FF8A6B',
    },
  },
  {
    name: 'Groups',
    key: 'groups',
    purpose: 'People, communities and shared spaces',
    light: {
      bg: '#F9F3EC',
      surface: '#FFFFFF',
      surface2: '#F0E7DB',
      ink: '#211913',
      muted: '#7A6E60',
      accent: '#F58A1E',
      accent2: '#FFB55A',
      onAccent: '#201206',
      positive: '#2FA35B',
      negative: '#E5533D',
    },
    dark: {
      bg: '#16100C',
      surface: '#241A12',
      surface2: '#2E2216',
      ink: '#F7EFE6',
      muted: '#A99A88',
      accent: '#FF9F45',
      accent2: '#FFC978',
      onAccent: '#1A1206',
      positive: '#8FE0A0',
      negative: '#FF6B6B',
    },
  },
  {
    name: 'Split',
    key: 'split',
    purpose: 'Balances, expenses and settlement',
    light: {
      bg: '#EDF6EF',
      surface: '#FFFFFF',
      surface2: '#E1EEE5',
      ink: '#12201A',
      muted: '#5F786D',
      accent: '#16A34A',
      accent2: '#22C55E',
      onAccent: '#FFFFFF',
      positive: '#16A34A',
      negative: '#E5533D',
    },
    dark: {
      bg: '#0D140F',
      surface: '#14201A',
      surface2: '#1B2A21',
      ink: '#ECF6EF',
      muted: '#8CA89A',
      accent: '#4ADE80',
      accent2: '#86EFAC',
      onAccent: '#052E16',
      positive: '#4ADE80',
      negative: '#FB7185',
    },
  },
  {
    name: 'Vibes',
    key: 'updates',
    purpose: 'Updates, reactions and social energy',
    light: {
      bg: '#FAF2EF',
      surface: '#FFFFFF',
      surface2: '#F3E4DE',
      ink: '#21140F',
      muted: '#7C6A62',
      accent: '#F86060',
      accent2: '#FFA23D',
      onAccent: '#200D0C',
      positive: '#2FA35B',
      negative: '#E5533D',
    },
    dark: {
      bg: '#15100F',
      surface: '#241A17',
      surface2: '#2E211D',
      ink: '#F8EFEA',
      muted: '#B09A92',
      accent: '#FF7A7A',
      accent2: '#FFB84D',
      onAccent: '#1E0D0C',
      positive: '#86EFAC',
      negative: '#F26A6A',
    },
  },
  {
    name: 'Profile',
    key: 'profile',
    purpose: 'Identity, preferences and personal space',
    light: {
      bg: '#F4F1F9',
      surface: '#FFFFFF',
      surface2: '#EAE4F3',
      ink: '#1B1626',
      muted: '#6E6683',
      accent: '#9B6DF2',
      accent2: '#E48FB6',
      onAccent: '#FFFFFF',
      positive: '#2FA35B',
      negative: '#E5533D',
    },
    dark: {
      bg: '#14101A',
      surface: '#201A2B',
      surface2: '#2A2338',
      ink: '#F3EEF8',
      muted: '#9E93AE',
      accent: '#C9A7FF',
      accent2: '#F5A9C4',
      onAccent: '#17101F',
      positive: '#A7F3D0',
      negative: '#FB7185',
    },
  },
] as const;

export const typographyScale = [
  {
    token: 'Display',
    family: 'Outfit',
    weight: '800',
    size: 44,
    lineHeight: 48,
    tracking: '-1 px',
    use: 'Launch moments and singular hero statements',
  },
  {
    token: 'Title',
    family: 'Outfit',
    weight: '700',
    size: 30,
    lineHeight: 34,
    tracking: '-0.5 px',
    use: 'Screen and modal titles',
  },
  {
    token: 'Heading',
    family: 'Outfit',
    weight: '700',
    size: 21,
    lineHeight: 26,
    tracking: 'Default',
    use: 'Sections and card groups',
  },
  {
    token: 'Body',
    family: 'Inter',
    weight: '400',
    size: 16,
    lineHeight: 22,
    tracking: 'Default',
    use: 'Primary reading and descriptions',
  },
  {
    token: 'Label',
    family: 'Inter',
    weight: '700',
    size: 14,
    lineHeight: 18,
    tracking: 'Default',
    use: 'Buttons, tabs and compact controls',
  },
  {
    token: 'Caption',
    family: 'Inter',
    weight: '400',
    size: 13,
    lineHeight: 17,
    tracking: 'Default',
    use: 'Metadata and supporting details',
  },
  {
    token: 'Mono',
    family: 'Space Mono',
    weight: '400',
    size: 14,
    lineHeight: 20,
    tracking: 'Default',
    use: 'Money, codes and technical values',
  },
] as const;

export const spacingScale = [
  { token: 'xs', value: 4 },
  { token: 'sm', value: 8 },
  { token: 'md', value: 12 },
  { token: 'lg', value: 16 },
  { token: 'xl', value: 24 },
  { token: '2xl', value: 32 },
  { token: '3xl', value: 48 },
] as const;

export const radiusScale = [
  { token: 'sm', value: 10, use: 'Small controls' },
  { token: 'md', value: 14, use: 'Menus and compact surfaces' },
  { token: 'lg', value: 20, use: 'Inputs and chips' },
  { token: 'xl', value: 28, use: 'Cards and sheets' },
  { token: 'pill', value: 999, use: 'Buttons, badges and avatars' },
] as const;

export const eventCategories = [
  { label: 'Hangout', icon: 'groups', emoji: '👋', tint: '#7FD1AE' },
  { label: 'Party', icon: 'celebration', emoji: '🎉', tint: '#F178B6' },
  { label: 'Meal', icon: 'restaurant', emoji: '🍽️', tint: '#F49B7A' },
  { label: 'Trip', icon: 'flight', emoji: '✈️', tint: '#6FB1FC' },
  { label: 'Sports', icon: 'sports-soccer', emoji: '⚽', tint: '#7BD389' },
  { label: 'Group Study', icon: 'menu-book', emoji: '📚', tint: '#B79CED' },
  { label: 'Movie', icon: 'movie', emoji: '🎬', tint: '#F5A97F' },
  { label: 'Concert', icon: 'music-note', emoji: '🎵', tint: '#C08CF0' },
  { label: 'Game Night', icon: 'sports-esports', emoji: '🎮', tint: '#6FD0C0' },
  { label: 'Birthday', icon: 'cake', emoji: '🎂', tint: '#F58AB0' },
  { label: 'Coffee', icon: 'local-cafe', emoji: '☕', tint: '#C9A27A' },
  { label: 'Drinks', icon: 'local-bar', emoji: '🍸', tint: '#E0A24E' },
  { label: 'Outdoors', icon: 'hiking', emoji: '🥾', tint: '#86C97F' },
  { label: 'Picnic', icon: 'outdoor-grill', emoji: '🧺', tint: '#9BCF7F' },
  { label: 'Road Trip', icon: 'directions-car', emoji: '🚗', tint: '#6FA8F0' },
  { label: 'Shopping', icon: 'shopping-bag', emoji: '🛍️', tint: '#EE9BC0' },
  { label: 'Festival', icon: 'festival', emoji: '🎪', tint: '#E58AC0' },
  { label: 'Workout', icon: 'fitness-center', emoji: '💪', tint: '#7BD389' },
  { label: 'Meeting', icon: 'event-note', emoji: '🤝', tint: '#F2C14E' },
  { label: 'Workshop', icon: 'build', emoji: '🛠️', tint: '#E8965A' },
  { label: 'Conference', icon: 'campaign', emoji: '🎤', tint: '#64C2C8' },
  { label: 'Event', icon: 'event', emoji: '📅', tint: '#8FB4F2' },
  { label: 'Other', icon: 'more-horiz', emoji: '✨', tint: '#C9CAD6' },
] as const;

export const vibeGradients = [
  { label: 'Movie', colors: ['#5B247A', '#7B2FF7', '#C4457E'], glow: '#F0B9FF' },
  { label: 'Sports', colors: ['#0F9B0F', '#2AB84B', '#A8E063'], glow: '#E4FFC2' },
  { label: 'Hangout', colors: ['#FF5E8A', '#FF8DA1', '#FFB199'], glow: '#FFE3D6' },
  { label: 'Walk', colors: ['#0BA18F', '#2BD68A', '#8FF7C4'], glow: '#D6FFEE' },
  { label: 'Food', colors: ['#F83600', '#FE8C00', '#FFC837'], glow: '#FFEAC2' },
  { label: 'Study', colors: ['#2148C0', '#3A6FE0', '#57C1EB'], glow: '#CFE8FF' },
  { label: 'Gaming', colors: ['#7A00F5', '#B24BF3', '#E14BE1'], glow: '#EEC6FF' },
  { label: 'Travel', colors: ['#0575E6', '#3AC1E0', '#5FE0C8'], glow: '#CFF6FF' },
  { label: 'Shopping', colors: ['#EC008C', '#F55CA0', '#FC6767'], glow: '#FFD6E8' },
  { label: 'Workout', colors: ['#E5153C', '#F5484B', '#FF7A45'], glow: '#FFD2BE' },
  { label: 'Default', colors: ['#5E55E8', '#8A63F2', '#C637DA'], glow: '#DCC8FF' },
] as const;

export const groupSectionAccents = [
  { label: 'Buzz', light: '#47788D', dark: '#A8D8EA' },
  { label: 'Events', light: '#667A38', dark: '#D5E6A3' },
  { label: 'Den', light: '#8D506D', dark: '#E8AAC8' },
  { label: 'Stats', light: '#4C796A', dark: '#A8D9C8' },
  { label: 'MVP', light: '#806D3A', dark: '#E6D49A' },
] as const;

export const statusGradients = [
  { label: 'Night', colors: ['#141E30', '#243B55'] },
  { label: 'Deep teal', colors: ['#0F2027', '#2C5364'] },
  { label: 'Deep purple', colors: ['#8E2DE2', '#4A00E0'] },
  { label: 'Slate', colors: ['#536976', '#292E49'] },
  { label: 'Violet', colors: ['#7F00FF', '#E100FF'] },
  { label: 'Fire', colors: ['#F00000', '#DC281E'] },
  { label: 'Steel blue', colors: ['#2980B9', '#2C3E50'] },
  { label: 'Plum', colors: ['#C6426E', '#642B73'] },
  { label: 'Royal blue', colors: ['#396AFC', '#2948FF'] },
  { label: 'Sky teal', colors: ['#1A2980', '#26D0CE'] },
  { label: 'Grape', colors: ['#DA22FF', '#9733EE'] },
  { label: 'Earth', colors: ['#603813', '#B29F94'] },
  { label: 'Coral pink', colors: ['#FF512F', '#DD2476'] },
  { label: 'Magenta', colors: ['#F953C6', '#B91D73'] },
  { label: 'Rose', colors: ['#EC008C', '#FC6767'] },
  { label: 'Indigo', colors: ['#4776E6', '#8E54E9'] },
  { label: 'Red coral', colors: ['#EB3349', '#F45C43'] },
  { label: 'Aqua', colors: ['#02AAB0', '#00CDAC'] },
  { label: 'Amber flame', colors: ['#F83600', '#FE8C00'] },
  { label: 'Moss', colors: ['#334D50', '#CBCAA5'] },
  { label: 'Emerald', colors: ['#11998E', '#38EF7D'] },
  { label: 'Lime green', colors: ['#00B09B', '#96C93D'] },
  { label: 'Sunset', colors: ['#FF6B6B', '#FF8E53'] },
  { label: 'Peach', colors: ['#DD5E89', '#F7BB97'] },
  { label: 'Mango', colors: ['#FDC830', '#F37335'] },
  { label: 'Gold', colors: ['#F7971E', '#FFD200'] },
] as const;

export const statusSolids = [
  { label: 'Coral', value: '#D94F59' },
  { label: 'Berry', value: '#B63E6F' },
  { label: 'Grape', value: '#7042B8' },
  { label: 'Indigo', value: '#4054B2' },
  { label: 'Cobalt', value: '#2463A6' },
  { label: 'Teal', value: '#167C80' },
  { label: 'Forest', value: '#26734D' },
  { label: 'Olive', value: '#6F7E32' },
  { label: 'Amber', value: '#B66A16' },
  { label: 'Tangerine', value: '#D35F32' },
  { label: 'Slate', value: '#475569' },
  { label: 'Charcoal', value: '#292929' },
] as const;
